id = "zed-obscion"
name = "Zed Obscion"
version = "0.0.1"
schema_version = 1
authors = ["Obscion"]
description = "A dark theme with warm, vibrant colors inspired by obsidian"
repository = "https://github.com/heyobscion/zed-obscion"
